INSERT INTO LOGS ( FIRST_CARD_NAME,FIRST_CARD_VALUE,FIRST_CARD_SUIT,SECOND_CARD_NAME,SECOND_CARD_VALUE,SECOND_CARD_SUIT,BET,IS_WIN) VALUES
( 'Ten',10,'CLUB','Ten',10,'CLUB','SUIT',1),
( 'Ace',14,'SPADE','Ten',10,'CLUB','HIGHER',0);
