DROP TABLE IF EXISTS LOGS;

CREATE TABLE LOGS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_CARD_NAME VARCHAR(50) NOT NULL,
    FIRST_CARD_VALUE INT NOT NULL,
    FIRST_CARD_SUIT VARCHAR(50) NOT NULL,
    SECOND_CARD_NAME VARCHAR(50) NOT NULL,
    SECOND_CARD_VALUE INT NOT NULL,
    SECOND_CARD_SUIT VARCHAR(50) NOT NULL,
    BET VARCHAR(50) NOT NULL,
    IS_WIN INT NOT NULL
);